/*#pragma config(Sensor, S1,     color_left,     sensorEV3_Color)
#pragma config(Sensor, S2,     color_right,    sensorEV3_Color)
#pragma config(Motor,  motorA,          arm,           tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Medium, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          slider,        tmotorEV3_Large, PIDControl, encoder)*/
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float radius=2.475;
float width=17.22;
float prev=0;
//float integrator=0;
float  line_follower(int set_point, int measurement){
	float kp=0.3, ki=0.00005, kd=3; //0.4 0.00005 2
	float error=set_point-measurement;
	float error_change=error-prev;
	float output=error*kp+integrator*ki+error_change*kd;
	integrator+=error;
	prev=error;
	return output;
}
void move_on_line(int speed,int side){
	resetMotorEncoder(LF);
	resetMotorEncoder(RG);
	clearTimer(T1);
	repeat(forever){
		float measurement=getColorReflected(LI);
		float output=line_follower(40, measurement);
		if(side==0){//marjvena
			setMotorSpeed(LF,speed+output);
			setMotorSpeed(RG, speed-output);
		}else if(side==1){
			setMotorSpeed(LF,speed-output);
			setMotorSpeed(RG, speed+output);
		}
		if(getColorReflected(LI)<12){
			setMotorSpeed(LF, 0);
			setMotorSpeed(RG, 0);
			break;
		}
	}
}
void move_on_line_dist(int speed,int side, float dist){
	resetMotorEncoder(LF);
	resetMotorEncoder(RG);
	sleep(100);
	//clearTimer(T1);
	int degree=(dist/(2*radius*PI))*360;
	repeat(forever){
		float measurement=getColorReflected(LI);
		float output=line_follower(40, measurement);
		if(side==0){
		setMotorSpeed(LF,speed+output);
		setMotorSpeed(RG, speed-output);
	}else{
		setMotorSpeed(LF,speed-output);
		setMotorSpeed(RG, speed+output);
	}
		if(abs(getMotorEncoder(LF))>=degree&&abs(getMotorEncoder(RG))>=degree ){
			setMotorSpeed(LF, 0);
			setMotorSpeed(RG, 0);
			break;
		}
	}
}
void move_distance(int speed, int dis){
	float degree=(dis/(2*radius*PI))*360;
	setMotorTarget(LF, degree, speed);
	setMotorTarget(RG, degree, speed);
}
void move_straight(float distance, int speed123) {
	integrator=0;
	nMotorEncoder[LF] = 0; // Reset left motor encoder
    nMotorEncoder[RG] = 0; // Reset right motor encoder
		//playSound(soundFastUpwardTones);
    int target = distance * 360 / (3.14 * 4.95) ; // Convert distance to encoder ticks
    repeat(forever){
        float measurement = nMotorEncoder[LF] + nMotorEncoder[RG];
        float diff =PID_haeri(0, measurement);
        setMotorSpeed(LF, speed123 -diff);
        setMotorSpeed(RG, speed123 +diff);
        if(abs(nMotorEncoder[LF])>=target){
        setMotorSpeed(LF, 0);
        setMotorSpeed(RG, 0);
        break;
      	}
    }
}
void nostop_move_straight(float distance, int speed123) {
	integrator=0;
	nMotorEncoder[LF] = 0; // Reset left motor encoder
    nMotorEncoder[RG] = 0; // Reset right motor encoder
		//playSound(soundFastUpwardTones);
    int target = distance * 360 / (3.14 * 4.95) ; // Convert distance to encoder ticks
    repeat(forever){
        float measurement = nMotorEncoder[LF] + nMotorEncoder[RG];
        float diff =PID_haeri(0, measurement);
        setMotorSpeed(LF, speed123 -diff);
        setMotorSpeed(RG, speed123 +diff);
        if(abs(nMotorEncoder[LF])>=target){
        //setMotorSpeed(LF, 0);
        //setMotorSpeed(RG, 0);
        break;
      	}
    }
}
void move_straight_blackwhite(int speed123, int col) {
	nMotorEncoder[LF] = 0; // Reset left motor encoder
    nMotorEncoder[RG] = 0; // Reset right motor encoder
    repeat(forever){
        float measurement = nMotorEncoder[LF] + nMotorEncoder[RG];
        float diff =PID_haeri(0, measurement);
        setMotorSpeed(LF, speed123 -diff);
        setMotorSpeed(RG, speed123 +diff);
        if(col==0&&getColorReflected(LI)<=12){

      	}else if(col==1&&getColorReflected(LI)>=60){
      		setMotorSpeed(LF, 0);
        	setMotorSpeed(RG, 0);
        	break;
      	}
    }
}
